services:
  srv-iot-ms:
    build:
      context: .
    image: srv-iot-ms
    container_name: srv-iot-ms
    ports:
      - 8001:8001
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
