name: IoT Service Deployment

on:
  release:
    types: [published]

jobs:
  environment:
    name: Environment Config
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        env:
          IOT_SERVICE_ENV: ${{ secrets.IOT_SERVICE_ENV }}
        run: |
          echo "$IOT_SERVICE_ENV" >> ./iot/.env

  deploy:
    needs: environment
    name: Start PM2 Service
    runs-on: self-hosted

    steps:
      - name: Set up Python 3.8.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.8"
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Start the server
        run: |
          pm2 stop "srv-iot-ms" || true
          pm2 delete "srv-iot-ms" || true
          pm2 start "FLASK_ENV=production FLASK_APP=iot/app.py flask run --port=6000 --host=0.0.0.0" -n "srv-iot-ms" -f
